{
 "title": "告警列表",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "esenv", "label": "告警环境", "query": "elasticsearch" },
   {
    "name": "alertLevel",
    "label": "告警等级",
    "query": "{\"find\": \"terms\", \"field\": \"level.keyword\"}"
   },
   {
    "name": "alertName",
    "label": "告警名称",
    "query": "{\"find\": \"terms\", \"field\": \"alertname.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "P0级别告警数量",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "level.keyword: \"0\"",
     "timeField": "created"
    }
   ]
  },
  {
   "title": "P1级别告警数量",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "level.keyword: \"1\"",
     "timeField": "created"
    }
   ]
  },
  {
   "title": "P2级别告警数量",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "level.keyword: \"2\"",
     "timeField": "created"
    }
   ]
  },
  {
   "title": "告警分类",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "alertname.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "created"
    }
   ]
  },
  {
   "title": "告警总数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "created"
    }
   ]
  },
  {
   "title": "告警趋势图",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status.keyword: \"firing\"",
     "timeField": "created"
    }
   ]
  },
  {
   "title": "告警详情",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "level.keyword: $alertLevel AND\nalertname.keyword: $alertName",
     "timeField": "created"
    }
   ]
  }
 ]
}